
package com.vodafone.group.contract.vbs.customer.customer_service_usage.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.vodafone.group.schema.vbm.customer.customer_service_usage.v1.GetCustomerServiceUsageListVBMRequestType;
import com.vodafone.group.schema.vbm.customer.customer_service_usage.v1.GetCustomerServiceUsageListVBMResponseType;


/**
 * 
 * 			This interface contains operations for the CustomerServiceUsage API
 * 		
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceUsageInterface", targetNamespace = "http://group.vodafone.com/contract/vbs/customer/customer-service-usage/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.vodafone.group.contract.vho.header.v1.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    com.vodafone.group.contract.vfo.fault.v1.ObjectFactory.class,
    un.unece.uncefact.documentation.standard.corecomponenttype._2.ObjectFactory.class,
    com.vodafone.group.schema.common.v1.ObjectFactory.class,
    com.vodafone.group.schema.vbo.customer.customer_service_usage.v1.ObjectFactory.class,
    com.vodafone.group.schema.extension.vbo.customer.customer_service_usage.v1.ObjectFactory.class,
    com.vodafone.group.schema.vbm.customer.customer_service_usage.v1.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class
})
public interface CustomerServiceUsageInterface {


    /**
     * 
     * 				This operation is used to GetCustomerServiceUsageList
     * 			
     * 
     * @param customerServiceUsageCriteria
     * @return
     *     returns com.vodafone.group.schema.vbm.customer.customer_service_usage.v1.GetCustomerServiceUsageListVBMResponseType
     * @throws VodafoneFault
     */
    @WebMethod(operationName = "GetCustomerServiceUsageList", action = "http://group.vodafone.com/contract/vbs/customer/customer-service-usage/v1/get-list")
    @WebResult(name = "GetCustomerServiceUsageListVBMResponse", targetNamespace = "http://group.vodafone.com/schema/vbm/customer/customer-service-usage/v1", partName = "CustomerServiceUsageList")
    public GetCustomerServiceUsageListVBMResponseType getCustomerServiceUsageList(
        @WebParam(name = "GetCustomerServiceUsageListVBMRequest", targetNamespace = "http://group.vodafone.com/schema/vbm/customer/customer-service-usage/v1", partName = "CustomerServiceUsageCriteria")
        GetCustomerServiceUsageListVBMRequestType customerServiceUsageCriteria)
        throws VodafoneFault
    ;

}
