
package com.vodafone.group.contract.vbs.customer.customer_service_usage.v1;

import javax.xml.ws.WebFault;
import com.vodafone.group.contract.vfo.fault.v1.FaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://group.vodafone.com/contract/vfo/fault/v1")
public class VodafoneFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public VodafoneFault(String message, FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public VodafoneFault(String message, FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vodafone.group.contract.vfo.fault.v1.FaultType
     */
    public FaultType getFaultInfo() {
        return faultInfo;
    }

}
